pipeline:
  - lint
  - unittest

jobs:
  lint:
    architectures: amd64
    series: focal
    packages:
      - tox
    run: |
      tox -e lint
  unittest:
    architectures: amd64
    series: focal
    packages:
      - tox
    run: |
      tox -e unit
